services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpswd
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
